batch.chunk.size=100

law.api.base-url=https://www.law.go.kr/DRF/lawService.do
law.api.oc=test
law.api.timeout-seconds=30

#?? ???
law.api.law-id-list=001561,003814,007388 
law.json.dir=./build/law-json
