application.name=project-core
upload.location=${java.io.tmpdir}

jwt.secret: ${JWT_SECRET:e37f6c9a9f21bc7d86fcbceb1c2593fb3e9fb4ef5c4f639feeb5d886b84eb066}
jwt.expiration: 86400000
jwt.refresh-expiration: 604800000