application.name=project-core
upload.location=C:/temp
profile.image.max-size-bytes=10485760
fastapi.base-url=http://localhost:8000

jwt.secret=35686b744fefe1201f1b6833c4895159fb124ec9e74de3141b3e228522acccc00f6faab33e62b262a1e47e0b41f3679e3364fa49cb372f50bac7a41b95dfc8c3
jwt.expiration=86400000
jwt.refresh-expiration=604800000

kakao.local.base-url=https://dapi.kakao.com
kakao.rest-api-key=21d26894462d47f173e99440a22dbb91

ai.conversation.crypto.active-key-id=v1
ai.conversation.crypto.key-v1=KSE3J98IRm5jBptMtQGoyaGQuufoceXzUm/OkJtChfE=
ai.conversation.crypto.key-v2=

clova.ocr.invoke-url=https://dv5mjdcze3.apigw.ntruss.com/custom/v1/56838/1ae18701c2165c14098a5a6ec44a3c37fb395a5f80ef99ff19e6b0f34e7c323c/general
clova.ocr.secret=anJUTU9QT3lJY016ckpQc25IV3N4SEZHVUdyYlloT3M=

pii.search.hmac-key-v1=sELpQCW4oupE8SgjtAeucA5/R04RLP9zrk1c32ZVgDk=
